/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author MARIA
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        bg2 = new javax.swing.JPanel();
        libreriaG8 = new javax.swing.JLabel();
        libro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        iniciar_sesion = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        escribir_su_usuario = new javax.swing.JTextField();
        escribir_contraseña = new javax.swing.JPasswordField();
        check = new javax.swing.JCheckBox();
        ingresar = new javax.swing.JButton();
        registrarse = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/fondo.jpg"))); // NOI18N
        fondo.setText("jdbejbejdbjbd");
        fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg2.setBackground(new java.awt.Color(204, 255, 102));

        libreriaG8.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        libreriaG8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libreriaG8.setText("Librería G8");
        libreriaG8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        libreriaG8.setMaximumSize(new java.awt.Dimension(80, 30));
        libreriaG8.setPreferredSize(new java.awt.Dimension(70, 20));

        libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro.jpg"))); // NOI18N
        libro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setBackground(new java.awt.Color(51, 102, 0));

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(libro))
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(libreriaG8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(libreriaG8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(libro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        bg.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 416));

        iniciar_sesion.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        iniciar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        iniciar_sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciar_sesion.setText("INICIAR SESIÓN");
        getContentPane().add(iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 290, 80));

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario:");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 120, 30));

        contraseña.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("Contraseña:");
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 140, 30));

        escribir_su_usuario.setBackground(new java.awt.Color(147, 147, 147));
        escribir_su_usuario.setForeground(new java.awt.Color(204, 204, 204));
        escribir_su_usuario.setText("Ecribir su usuario");
        escribir_su_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escribir_su_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(escribir_su_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 220, -1));

        escribir_contraseña.setBackground(new java.awt.Color(145, 145, 145));
        escribir_contraseña.setForeground(new java.awt.Color(204, 204, 204));
        escribir_contraseña.setText("jPasswordField1");
        getContentPane().add(escribir_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 220, -1));

        check.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setText("Recordar contraseña");
        getContentPane().add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 160, -1));

        ingresar.setBackground(new java.awt.Color(102, 255, 0));
        ingresar.setText("Ingresar");
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 110, -1));

        registrarse.setBackground(new java.awt.Color(204, 0, 0));
        registrarse.setText("Registrarse");
        getContentPane().add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 110, -1));

        fondo1.setBackground(new java.awt.Color(104, 104, 104));
        fondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        fondo1.setLabelFor(fondo1);
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -10, 620, 430));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(5, 203, 253));
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 300, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escribir_su_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escribir_su_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escribir_su_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg2;
    private javax.swing.JCheckBox check;
    private javax.swing.JLabel contraseña;
    private javax.swing.JPasswordField escribir_contraseña;
    private javax.swing.JTextField escribir_su_usuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel iniciar_sesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel libreriaG8;
    private javax.swing.JLabel libro;
    private javax.swing.JButton registrarse;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
