/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author ferna
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg2 = new javax.swing.JPanel();
        libreriaG8 = new javax.swing.JLabel();
        logoPrincipal = new javax.swing.JLabel();
        iniciar_sesion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        escribir_su_usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        escribir_contraseña = new javax.swing.JPasswordField();
        check = new javax.swing.JCheckBox();
        registrarse = new javax.swing.JButton();
        ingresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        bg2.setBackground(new java.awt.Color(255, 255, 51));

        libreriaG8.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        libreriaG8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libreriaG8.setText("Librería G8");
        libreriaG8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        libreriaG8.setMaximumSize(new java.awt.Dimension(80, 30));
        libreriaG8.setPreferredSize(new java.awt.Dimension(70, 20));

        logoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro.jpg"))); // NOI18N

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libreriaG8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(libreriaG8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        iniciar_sesion.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        iniciar_sesion.setForeground(new java.awt.Color(0, 153, 153));
        iniciar_sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciar_sesion.setText("INICIAR SESIÓN");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuario");

        escribir_su_usuario.setBackground(new java.awt.Color(147, 147, 147));
        escribir_su_usuario.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        escribir_su_usuario.setForeground(new java.awt.Color(204, 204, 204));
        escribir_su_usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        escribir_su_usuario.setText("Escribir su usuario");
        escribir_su_usuario.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        escribir_su_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escribir_su_usuarioActionPerformed(evt);
            }
        });

        contraseña.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(0, 0, 0));
        contraseña.setText("Contraseña:");

        escribir_contraseña.setBackground(new java.awt.Color(145, 145, 145));
        escribir_contraseña.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        escribir_contraseña.setForeground(new java.awt.Color(204, 204, 204));
        escribir_contraseña.setText("jPasswordField1");

        check.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setText("Recordar contraseña");

        registrarse.setBackground(new java.awt.Color(204, 0, 0));
        registrarse.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        registrarse.setText("Registrarse");

        ingresar.setBackground(new java.awt.Color(102, 255, 0));
        ingresar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ingresar.setText("Ingresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 347, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(320, 320, 320)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(iniciar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(escribir_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(escribir_su_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(registrarse)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(iniciar_sesion)
                    .addGap(61, 61, 61)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(escribir_su_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(contraseña)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(escribir_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(check)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registrarse)
                        .addComponent(ingresar))
                    .addContainerGap(44, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escribir_su_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escribir_su_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escribir_su_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg2;
    private javax.swing.JCheckBox check;
    private javax.swing.JLabel contraseña;
    private javax.swing.JPasswordField escribir_contraseña;
    private javax.swing.JTextField escribir_su_usuario;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel iniciar_sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel libreriaG8;
    private javax.swing.JLabel logoPrincipal;
    private javax.swing.JButton registrarse;
    // End of variables declaration//GEN-END:variables
}
